language: python
python:
  - "3.4"

git:
  depth: 3

addons:
  chrome: stable

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvbf some time to start

install:
  - pip install -r dev_requirements.txt

script:
  - python test/replay_button_click.py

