language: python
python:
  - "3.4"

node_js:
  - "6.11"

git:
  depth: 3

addons:
  chrome: stable

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvbf some time to start

install:
  - wget http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - pip install -r dev_requirements.txt

script:
  - python test/integration/replay_button_click.py
  - npm test

